services:
  - type: web
    name: pharmacy-backend
    runtime: docker
    rootDir: pharmacy-backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
