services:
  - type: web
    name: pharmacy-backend
    runtime: java
    rootDir: pharmacy-backend
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/pharmacy-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
